services:
  openas2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4080:10080
      - 4081:10081
      - ${HOST_RESTAPI_PORT:-8443}:8080
    environment:
      - OPENAS2PROP_RESTAPI__COMMAND__PROCESSOR__BASEURI=http://0.0.0.0:8080
      - OPENAS2PROP_RESTAPI__COMMAND__PROCESSOR__USERID=userID
      - OPENAS2PROP_RESTAPI__COMMAND__PROCESSOR__PASSWORD=pWd
      - OPENAS2PROP_RESTAPI__COMMAND__PROCESSOR__ENABLED=true
    tty: true
    stdin_open: true
    volumes:
      - ./config:/opt/openas2/config:rw
      - ./data:/opt/openas2/data:rw


  openas2_webui:
    build:
      context: .
      dockerfile: Dockerfile_WebUI
      args:
        - VUE_APP_RESTAPI_URL=http://localhost:${HOST_RESTAPI_PORT:-8443}/api
    ports:
      - ${HOST_WEBUI_PORT:-8080}:80
    tty: true
    stdin_open: true
volumes:
  config:
  data: