FROM node:21-alpine AS web-builder
RUN npm install -g --force yarn
COPY ./WebUI /usr/src/webui
WORKDIR /usr/src/webui
RUN yarn install
RUN npx browserslist@latest --update-db
ARG VUE_APP_RESTAPI_URL
ENV VUE_APP_RESTAPI_URL=${VUE_APP_RESTAPI_URL:-http://localhost:8080}
RUN yarn run build

FROM nginx:stable-alpine
COPY --from=web-builder /usr/src/webui/dist /usr/share/nginx/html